Fix for export error
Whenever I try to add this to a typescript project, I get the following error:

node_modules/recombee-api-client/lib/index.d.ts:1:1 - error TS2668: 'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible.

Changing "export" to "declare" appears to fix the problem.